repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        stages: [commit]
        language: system
        types: [python]
        entry: ruff
        args: [--fix]

      - id: black
        name: black
        stages: [commit]
        language: system
        types: [python]
        entry: black

      - id: pytest
        name: pytest
        stages: [push]
        language: system
        entry: pytest --cov
        types: [python]
        pass_filenames: false
