exclude: ^src/ui/
fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.290
    hooks:
    - id: ruff
      stages: [commit]
      args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks: 
    - id: black
      stages: [commit]
      args: [--line-length, "100"]
