development:
  port: 8000
  host: 0.0.0.0
  DEBUG: true

  logging:
    destination: null
    level: DEBUG

  modules:
    training:
      path: ./data/training_samples.json

production:
  port: 8008
  host: 0.0.0.0

  logging:
    destination: null
    level: INFO

  modules:
    runtime: {}
